baseURL = 'https://blog.alright21.me'
languageCode = 'en-us'
title = 'Alberto Giust'
theme = 'hugo-theme-cactus'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Security"
url = "/security"
weight = 2

[[menu.main]]
name = "CTFs"
url = "/ctf"
weight = 3

[[menu.main]]
name = "Education"
url = "/education"
weight = 4

[[menu.main]]
name = "Dev"
url = "/dev"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 6


[params]

    colortheme = "dark"
    rss = true
    show_updated = true
    showReadTime = true

    # Main Page
    description = "Hi, I am Alberto Giust, aka `alright(21)?`, penetration tester at Spike Reply and security enthusiast. In this website you will find CTF writeups and other interesting things I want to document about my journey through the magical world of Cybersecurity."
    mainSections = ["security","ctf","education","dev"]
    showAllPostsOnHomePage = true
    tagsOverview = false

    [[params.social]]
        name = "github"
        link = "https://github.com/alright21"
    [[params.social]]
        name = "email"
        link = "alberto.giust21@gmail.com"
    [[params.social]]
        name = "linkedin"
        link = "https://www.linkedin.com/in/alberto-giust/"
    [[params.social]]
        name = "twitter"
        link = "https://twitter.com/alright2121"

    [params.comments]
        enabled = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true